CREATE DATABASE DPUK;


CREATE schema project99;

CREATE TABLE project99.demdiag (
ACH_DATE VARCHAR(50),
PRACTICE_CODE VARCHAR(50),
"NAME" VARCHAR(50),
COMMISSIONER_ORGANISATION_CODE VARCHAR(50),
GEOGRAPHY_CODE VARCHAR(50),
Measure VARCHAR(50),
"Value" numeric
);

COPY project99.demdiag(ACH_DATE,PRACTICE_CODE,"NAME",COMMISSIONER_ORGANISATION_CODE,GEOGRAPHY_CODE,Measure,"Value") 
FROM '/data/rec-dem-diag-Sep-2022.csv'
DELIMITER ','
CSV HEADER;